#pragma once

#include "sdkconfig.h"

#ifndef CONFIG_OTOOL_ESP_HOSTED_FW_CHUNK_SIZE
#define CONFIG_OTOOL_ESP_HOSTED_FW_CHUNK_SIZE 1024
#endif

#ifndef CONFIG_OTOOL_ESP_HOSTED_FW_FAIL_ON_HOST_NEWER_MAJOR_MINOR
#define CONFIG_OTOOL_ESP_HOSTED_FW_FAIL_ON_HOST_NEWER_MAJOR_MINOR 0
#endif

